---
layout: post
title: 200305_TIL
category: TIL
tags: [TIL]
comments: true
---

# 오늘 한 일
#### python
자기전에 기능 추가하고 자려했는데, 계속 오류가 나타나는 것이다.
무엇이 문제인지 계속 사태를 벌이다가 아주 허무하게 해결했는데, 한 메소드가 오타낸 것이었다... select라 할 것을 seclet로 했던 것이다.

딕셔너리와 enumerate를 같이 쓸 때는 튜플로 묶어줘야 한다.
```python
for num, (key, item) in enumerate(딕셔너리.items()):
    print(num, key, item)
```


# 느낀 점
오타가 안나도록 꼼꼼히 봐야겠다.

# 내일 할 일
예외 처리에 대해 공부하기
